version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: proofledger_postgres
    restart: always
    environment:
      POSTGRES_USER: proofledger_user
      POSTGRES_PASSWORD: proofledger_pass
      POSTGRES_DB: proofledger_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U proofledger_user -d proofledger_db']
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: proofledger_minio
    restart: always
    environment:
      MINIO_ROOT_USER: proofledger_minio
      MINIO_ROOT_PASSWORD: proofledger_minio_pass
    command: server /data --console-address ":9001"
    ports:
      - '9090:9000'
      - '9091:9001'
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
